# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

name: FBGEMM_GPU Lint

on:
  # PR Trigger
  #
  push:
    branches:
      - main

  # Push Trigger (enable to catch errors coming out of multiple merges)
  #
  pull_request:
    branches:
      - main

concurrency:
  # Cancel previous runs in the PR if a new commit is pushed
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install click flake8 ufmt

    - name: Analyzing the Code with flake8
      run: |
        echo "::add-matcher::fbgemm_gpu/test/lint/flake8_problem_matcher.json"
        flake8 --ignore=E501,W503,E203 .
        # E501 = line too long
        # W503 = line break before binary operator (deprecated)
        # E203 = whitespace before ":"

    - name: Analyzing the Code with ufmt
      run: |
        ufmt diff fbgemm_gpu/fbgemm_gpu
        ufmt diff fbgemm_gpu/test
        ufmt diff fbgemm_gpu/bench

    - name: Check Meta Copyright Header
      run: |
        python fbgemm_gpu/test/lint/check_meta_header.py --path=./fbgemm_gpu/fbgemm_gpu --fixit=False
        python fbgemm_gpu/test/lint/check_meta_header.py --path=./fbgemm_gpu/test --fixit=False
        python fbgemm_gpu/test/lint/check_meta_header.py --path=./fbgemm_gpu/bench --fixit=False
